
name: ecoinnovators
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - ultralytics
      - opencv-python
      - numpy
      - pandas
      - shapely
      - requests
      - Pillow
      - openpyxl

      
